[build]
  command = "chmod +x build_files.sh && ./build_files.sh && mkdir -p public/static && cp -r staticfiles/* public/static/"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
