# Generated by Django 6.0 on 2025-12-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('code', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quntity', models.IntegerField(default=0)),
                ('gst', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='rdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=128)),
                ('phone_number', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
