# Generated by Django 6.0 on 2025-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='password',
        ),
        migrations.AddField(
            model_name='password',
            name='npassword',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='password',
            name='opassword',
            field=models.IntegerField(default=0),
        ),
    ]
