# Generated by Django 6.0 on 2025-12-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0004_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pro',
            old_name='quntity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='rdb',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='password',
            name='npassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='password',
            name='opassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pro',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rdb',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
