# Generated by Django 6.0 on 2025-12-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0005_rename_quntity_pro_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdb',
            name='code',
            field=models.CharField(default='000', max_length=500),
        ),
    ]
