# Generated by Django 6.0 on 2025-12-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0006_rdb_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdb',
            old_name='code',
            new_name='password',
        ),
    ]
