# Generated by Django 6.0 on 2025-12-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0003_remove_password_password_password_npassword_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='od',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeer_num', models.CharField(max_length=50, null=True)),
                ('oder_date', models.DateField(null=True)),
                ('cs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('ps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rs.pro')),
            ],
        ),
    ]
