# Generated by Django 6.0 on 2025-12-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_od'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='od',
            name='ps',
        ),
    ]
